import React, { useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, TextInput, Modal, Alert } from 'react-native';
import { C, s } from '../styles/progresoStyles';
import { EJERCICIOS, GRUPOS, MEDIDAS, PERIODOS, SEMANAS, SESIONES, topEjercicios, topGruposMedida, topGruposPeso } from '../data/progresoMock';

function Header({ navigation }) {
  return <><View style={s.status}><Text style={s.time}>9:41</Text><Text style={s.icons}>▲ WiFi 🔋</Text></View><View style={s.header}><TouchableOpacity onPress={() => navigation.navigate('Home')}><Text style={s.back}>←</Text></TouchableOpacity><Text style={s.title}>Progreso</Text><View style={{ width: 28 }} /></View></>;
}
function Badge() { return <View style={s.badge}><Text style={s.badgeText}>RF50–RF57</Text></View>; }
function Tabs({ tab, setTab }) { return <View style={s.tabs}>{[['resumen', 'Resumen'], ['ejercicio', 'Por ejercicio'], ['consistencia', 'Consistencia']].map(x => <TouchableOpacity key={x[0]} onPress={() => setTab(x[0])} style={[s.tab, tab === x[0] && s.tabOn]}><Text style={[s.tabTxt, tab === x[0] && s.tabTxtOn]}>{x[1]}</Text></TouchableOpacity>)}</View>; }
function Periodos({ val, setVal }) { return <View style={s.chips}>{PERIODOS.map(p => <TouchableOpacity key={p.id} onPress={() => setVal(p.id)} style={[s.chip, val === p.id && s.chipOn]}><Text style={[s.chipText, val === p.id && s.chipTextOn]}>{p.t}</Text></TouchableOpacity>)}</View>; }
function Kpi({ icon, v, l, c }) { return <View style={s.kpi}><Text style={s.kIcon}>{icon}</Text><View><Text style={[s.kVal, { color: c }]}>{v}</Text><Text style={s.kLab}>{l}</Text></View></View>; }
function ExportButton({ text, onPress }) { return <TouchableOpacity style={s.primary} onPress={onPress}><Text style={s.primaryText}>📤 Exportar {text}</Text></TouchableOpacity>; }
function Bars({ values, color = C.purple }) { const max = Math.max(...values), min = Math.min(...values); return <View style={s.chart}><View style={s.bars}>{values.map((v, i) => <View key={i} style={[s.bar, { height: `${max === min ? 60 : 25 + ((v - min) / (max - min)) * 70}%`, backgroundColor: i === values.length - 1 ? color : C.soft }]} />)}</View></View>; }

function Medidas({ periodo, setPeriodo }) {
  const [open, setOpen] = useState(false);
  return <View style={s.card}>
    <TouchableOpacity style={s.between} onPress={() => setOpen(!open)}><View><Text style={s.cardTitle}>Medidas corporales</Text><Text style={s.sub}>Base vs actual · toca para {open ? 'ocultar' : 'ver detalle'}</Text></View><Text style={s.arrow}>{open ? '⌃' : '⌄'}</Text></TouchableOpacity>
    <View style={s.radar}><View style={s.rLineV} /><View style={s.rLineH} /><View style={s.rLineA} /><View style={s.rLineB} /><View style={s.rBase} /><View style={s.rNow} />{['Pecho', 'Brazo', 'Pantorrilla', 'Muslo', 'Cadera', 'Cintura'].map((x, i) => <Text key={x} style={[s.rLab, s[`rp${i}`]]}>{x}</Text>)}</View>
    <View style={s.legend}><Text style={s.legendText}>◈ Base</Text><Text style={[s.legendText, { color: C.purple }]}>◈ Actual</Text></View>
    {open && <View style={s.measureGrid}>{MEDIDAS.map(m => <View key={m[0]} style={s.measure}><Text style={s.mName}>{m[0]}</Text><Text style={s.mBase}>Base {m[1]}cm</Text><Text style={s.mNow}>Actual {m[2]}cm</Text><Text style={[s.mDiff, { color: m[3] >= 0 ? C.green : C.red }]}>{m[3] > 0 ? '+' : ''}{m[3]} cm</Text></View>)}</View>}
    <Periodos val={periodo} setVal={setPeriodo} />
  </View>;
}
function FechaDrop({ label, value, setValue }) {
  const [open, setOpen] = useState(false), [q, setQ] = useState('');
  const selected = SESIONES.find(x => x.id === value);
  const list = SESIONES.filter(x => `${x.fecha} ${x.hora}`.toLowerCase().includes(q.toLowerCase()));
  return <View style={s.dropWrap}><Text style={s.tiny}>{label}</Text><TouchableOpacity style={s.selectBtn} onPress={() => setOpen(!open)}><Text style={s.selectTxt}>{selected.fecha.split(',')[0]} · {selected.hora}</Text><Text style={s.arrow}>{open ? '⌃' : '⌄'}</Text></TouchableOpacity>{open && <View style={s.dropdown}><TextInput style={s.input} placeholder="Buscar día o mes..." placeholderTextColor={C.sub} value={q} onChangeText={setQ} />{list.map(x => <TouchableOpacity key={x.id} style={[s.dropItem, value === x.id && s.dropOn]} onPress={() => { setValue(x.id); setOpen(false); setQ(''); }}><Text style={[s.dropText, value === x.id && s.dropTextOn]}>{x.fecha} · {x.hora}</Text></TouchableOpacity>)}</View>}</View>;
}
function Comparar() {
  const [a, setA] = useState(1), [b, setB] = useState(2); const A = SESIONES.find(x => x.id === a), B = SESIONES.find(x => x.id === b);
  const comunes = A.e.filter(ea => B.e.some(eb => eb.n === ea.n));
  return <View style={s.card}><Text style={s.cardTitle}>Comparar fechas</Text><Text style={s.sub}>Selecciona o busca sesiones por día/mes</Text><FechaDrop label="Fecha A" value={a} setValue={setA} /><FechaDrop label="Fecha B" value={b} setValue={setB} /><View style={s.divider} />{comunes.length ? comunes.map(ea => { const eb = B.e.find(x => x.n === ea.n); const ka = ea.s[0][1], kb = eb.s[0][1], d = kb - ka; return <View key={ea.n} style={s.common}><Text style={s.commonName}>{ea.ic} {ea.n}</Text><Text style={s.commonVal}>{ka}kg</Text><View style={{ alignItems: 'flex-end' }}><Text style={[s.commonVal, { color: C.teal }]}>{kb}kg</Text><Text style={[s.delta, { color: d > 0 ? C.green : d < 0 ? C.red : C.sub }]}>{d > 0 ? '+' : ''}{d}kg</Text></View></View>; }) : <Text style={s.empty}>Sin ejercicios en común.</Text>}</View>;
}
function Resumen({ periodo, setPeriodo, navigation, exportar }) { return <><View style={s.kpiGrid}><Kpi icon="🔥" v="14 días" l="Racha actual" c={C.orange} /><Kpi icon="📊" v="85%" l="Adherencia" c={C.purple} /><Kpi icon="🏋️" v="24" l="Sesiones" c={C.green} /><Kpi icon="⬆️" v="18,420kg" l="Volumen" c={C.teal} /></View><Medidas periodo={periodo} setPeriodo={setPeriodo} /><View style={s.card}><Text style={s.cardTitle}>Entrenamientos recientes</Text>{SESIONES.slice(0, 4).map(x => <TouchableOpacity key={x.id} style={s.recent} onPress={() => navigation.navigate('HistorialSesiones')}><View style={s.dateBox}><Text style={s.dateM}>{x.fecha.split(' ')[0]}</Text><Text style={s.dateD}>{x.fecha.split(' ')[1].replace(',', '')}</Text></View><View style={{ flex: 1 }}><Text style={s.rTitle}>{x.hora} · {x.dur}</Text><Text style={s.rSub}>{x.e.length} ejercicios · {x.vol}</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>)}</View><Comparar /><ExportButton text="resumen completo" onPress={exportar} /></>; }

function Mini({ v, l, green }) { return <View style={s.mini}><Text style={[s.miniVal, green && { color: C.green }]}>{v}</Text><Text style={s.miniLab}>{l}</Text></View>; }
function SesionEj({ item, prev, open, onPress }) { const max = Math.max(...item.s.map(x => x[1])); const pmax = prev ? Math.max(...prev.s.map(x => x[1])) : max; const d = max - pmax; const avg = Math.round(item.s.reduce((a, x) => a + parseInt(x[3], 10), 0) / item.s.length); return <View style={s.session}><TouchableOpacity style={s.sessionHead} onPress={onPress}><View><Text style={s.compDate}>{item.fecha}</Text><Text style={s.compSub}>{item.s.length} series · máx. {max}kg</Text></View><View style={{ alignItems: 'flex-end' }}><Text style={[s.deltaPill, { color: d > 0 ? C.green : d < 0 ? C.red : C.sub }]}>{d > 0 ? '+' : ''}{d}kg</Text><Text style={s.arrow}>{open ? '⌃' : '⌄'}</Text></View></TouchableOpacity>{open && <View style={s.series}><View style={s.tableHead}>{['Serie', 'Reps', 'Peso', 'Tiempo ejecución'].map(h => <Text key={h} style={s.th}>{h}</Text>)}</View>{item.s.map(r => <View key={r[0]} style={s.tr}><Text style={s.td}>{r[0]}</Text><Text style={s.td}>{r[2]}</Text><Text style={s.td}>{r[1]}kg</Text><Text style={s.td}>{r[3]}</Text></View>)}<View style={s.avg}><Text style={s.avgText}>Promedio de ejecución</Text><Text style={s.avgVal}>{avg}s</Text></View></View>}</View>; }
function Ejercicio({ selected, setSelected, grupo, setGrupo, periodo, setPeriodo, exportar }) {
  const [open, setOpen] = useState(null);
  const names = Object.keys(EJERCICIOS).filter(n => grupo === 'Todos' || EJERCICIOS[n][0] === grupo); const ej = EJERCICIOS[selected] || EJERCICIOS['Press de banca']; const gain = ej[3].at(-1) - ej[3][0];
  const sesiones = SESIONES.flatMap(x => x.e.filter(e => e.n === selected).map(e => ({ ...e, fecha: `${x.fecha} · ${x.hora}` })));
  return <><View style={s.card}><Text style={s.cardTitle}>Seleccionar ejercicio</Text><View style={s.chips}>{GRUPOS.map(g => <TouchableOpacity key={g} onPress={() => setGrupo(g)} style={[s.chip, grupo === g && s.chipOn]}><Text style={[s.chipText, grupo === g && s.chipTextOn]}>{g}</Text></TouchableOpacity>)}</View>{names.map(n => <TouchableOpacity key={n} onPress={() => setSelected(n)} style={[s.exercise, selected === n && s.exerciseOn]}><Text style={s.exIcon}>{EJERCICIOS[n][1]}</Text><View style={{ flex: 1 }}><Text style={s.exName}>{n}</Text><Text style={s.exSub}>{EJERCICIOS[n][0]} · {EJERCICIOS[n][3].length} registros</Text></View>{selected === n && <Text style={s.check}>✓</Text>}</TouchableOpacity>)}</View><View style={s.card}><View style={s.between}><View><Text style={s.cardTitle}>{selected}</Text><Text style={s.sub}>Evolución de carga</Text></View><Text style={[s.posBadge, { color: gain >= 0 ? C.green : C.red }]}>{gain >= 0 ? '+' : ''}{gain}{ej[2]}</Text></View><Periodos val={periodo} setVal={setPeriodo} /><Bars values={ej[3]} /><View style={s.miniGrid}><Mini v={`${Math.max(...ej[3])}${ej[2]}`} l="Máximo" /><Mini v={`${ej[3][0]}${ej[2]}`} l="Inicio" /><Mini v={`${gain >= 0 ? '+' : ''}${gain}${ej[2]}`} l="Cambio" green /></View></View><View style={s.card}><Text style={s.cardTitle}>Comparativo de sesiones</Text><Text style={s.sub}>Toca una sesión para ver series, reps, peso y tiempo</Text>{sesiones.length ? sesiones.map((x, i) => <SesionEj key={x.fecha} item={x} prev={sesiones[i + 1]} open={open === i} onPress={() => setOpen(open === i ? null : i)} />) : <Text style={s.empty}>Sin sesiones detalladas.</Text>}</View><ExportButton text="progreso por ejercicio" onPress={exportar} /></>;
}

function TopCard({ title, items, onPress }) { return <TouchableOpacity style={s.topCard} onPress={onPress}><View style={s.between}><Text style={s.cardTitle}>{title}</Text><Text style={s.arrow}>›</Text></View>{items.slice(0, 3).map((x, i) => <View key={x.label} style={s.compact}><Text style={s.compactN}>{i + 1}</Text><Text style={s.compactL}>{x.label}</Text><Text style={s.compactV}>+{x.val}{x.unit}</Text></View>)}</TouchableOpacity>; }
function Consistencia({ periodo, setPeriodo, exportar, openTop }) {
  const weeks = SEMANAS[periodo]; const avg = (weeks.reduce((a, b) => a + b, 0) / weeks.length).toFixed(1); const adh = Math.round((weeks.reduce((a, b) => a + b, 0) / (weeks.length * 3)) * 100);
  return <><View style={s.kpiGrid}><Kpi icon="🔥" v="14 días" l="Racha actual" c={C.orange} /><Kpi icon="📊" v={`${adh}%`} l="Adherencia" c={C.purple} /><Kpi icon="📅" v={avg} l="Prom./sem" c={C.teal} /><Kpi icon="🏆" v="21 días" l="Mejor racha" c={C.green} /></View><View style={s.card}><View style={s.between}><View><Text style={s.cardTitle}>Frecuencia semanal</Text><Text style={s.sub}>Objetivo semanal: 3 días</Text></View><Text style={s.goal}>Meta 3/sem</Text></View><Periodos val={periodo} setVal={setPeriodo} /><View style={s.legend}><Text style={[s.legendText, { color: C.green }]}>● Cumplido</Text><Text style={[s.legendText, { color: C.orange }]}>● Debajo del objetivo</Text></View><ScrollView horizontal={periodo === 'todo'} showsHorizontalScrollIndicator={periodo === 'todo'}><View style={[s.weekChart, periodo === 'todo' && { width: weeks.length * 38 }]}>{weeks.map((w, i) => <View key={i} style={s.weekCol}><View style={s.weekTrack}><View style={[s.weekBar, { height: `${Math.min(100, (w / 3) * 100)}%`, backgroundColor: w >= 3 ? C.green : C.orange }]} /></View><Text style={s.weekTxt}>S{i + 1}</Text></View>)}</View></ScrollView></View><View style={s.topGrid}><TopCard title="Top ejercicios" items={topEjercicios()} onPress={() => openTop('ejercicios')} /><TopCard title="Top grupos" items={topGruposPeso()} onPress={() => openTop('grupos')} /></View><ExportButton text="consistencia" onPress={exportar} /></>;
}

function ExportModal({ show, close, tab }) { const [fmt, setFmt] = useState('csv'); return <Modal visible={show} transparent animationType="slide"><View style={s.overlay}><View style={s.sheet}><View style={s.handle} /><Text style={s.modalTitle}>Exportar progreso</Text><Text style={s.sub}>Reporte de {tab === 'resumen' ? 'resumen completo' : tab === 'ejercicio' ? 'progreso por ejercicio' : 'consistencia'}</Text><View style={s.exportGrid}>{['csv', 'pdf'].map(f => <TouchableOpacity key={f} onPress={() => setFmt(f)} style={[s.exportOpt, fmt === f && s.exportOn]}><Text style={s.exportIcon}>{f === 'csv' ? '📊' : '📄'}</Text><Text style={[s.exportText, fmt === f && { color: C.purple }]}>{f.toUpperCase()}</Text></TouchableOpacity>)}</View><TouchableOpacity style={s.primary} onPress={() => { close(); Alert.alert('Exportación demo', `Se exportaría como ${fmt.toUpperCase()}.`); }}><Text style={s.primaryText}>Exportar como {fmt.toUpperCase()}</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={close}><Text style={s.secondaryText}>Cancelar</Text></TouchableOpacity></View></View></Modal>; }
function TopModal({ type, close }) { const [mode, setMode] = useState('pesos'); if (!type) return null; const items = type === 'ejercicios' ? topEjercicios().slice(0, 5) : mode === 'pesos' ? topGruposPeso() : topGruposMedida(); return <Modal visible transparent animationType="slide"><View style={s.overlay}><View style={s.sheet}><View style={s.handle} /><View style={s.between}><Text style={s.modalTitle}>{type === 'ejercicios' ? 'Top ejercicios' : 'Top grupos'}</Text><TouchableOpacity onPress={close}><Text style={s.close}>Cerrar</Text></TouchableOpacity></View>{type === 'grupos' && <View style={s.miniTabs}>{['pesos', 'medidas'].map(m => <TouchableOpacity key={m} onPress={() => setMode(m)} style={[s.miniTab, mode === m && s.miniOn]}><Text style={[s.miniTxt, mode === m && { color: 'white' }]}>{m}</Text></TouchableOpacity>)}</View>}{items.map((x, i) => <View key={x.label} style={s.rank}><View style={s.rankNum}><Text style={s.rankNumT}>{i + 1}</Text></View><View style={{ flex: 1 }}><Text style={s.rankLabel}>{x.label}</Text><Text style={s.sub}>{x.sub}</Text></View><Text style={s.rankVal}>+{x.val}{x.unit}</Text></View>)}</View></View></Modal>; }

export default function ProgresoScreen({ navigation }) {
  const [tab, setTab] = useState('resumen'), [pRes, setPRes] = useState('1m'), [pEj, setPEj] = useState('3m'), [pCon, setPCon] = useState('3m');
  const [ej, setEj] = useState('Press de banca'), [grupo, setGrupo] = useState('Todos'), [exp, setExp] = useState(false), [top, setTop] = useState(null);
  return <View style={s.container}><Header navigation={navigation} /><ScrollView contentContainerStyle={s.body} showsVerticalScrollIndicator={false}><Badge /><Tabs tab={tab} setTab={setTab} />{tab === 'resumen' && <Resumen periodo={pRes} setPeriodo={setPRes} navigation={navigation} exportar={() => setExp(true)} />}{tab === 'ejercicio' && <Ejercicio selected={ej} setSelected={setEj} grupo={grupo} setGrupo={setGrupo} periodo={pEj} setPeriodo={setPEj} exportar={() => setExp(true)} />}{tab === 'consistencia' && <Consistencia periodo={pCon} setPeriodo={setPCon} exportar={() => setExp(true)} openTop={setTop} />}</ScrollView><ExportModal show={exp} close={() => setExp(false)} tab={tab} /><TopModal type={top} close={() => setTop(null)} /></View>;
}
