import { StyleSheet } from 'react-native';

export const C = {
  bg: '#1a1a22', card: '#24242e', card2: '#2a2a35', soft: '#343440', border: '#3a3a46',
  text: '#f5f5f7', sub: '#8b8b98', purple: '#7c6fcd', teal: '#5eead4', orange: '#ffa032', green: '#34d399', red: '#f87171',
};

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  status: { paddingTop: 12, paddingHorizontal: 18, height: 42, flexDirection: 'row', justifyContent: 'space-between' },
  time: { color: C.text, fontWeight: '800', fontSize: 12 },
  icons: { color: C.text, fontSize: 10 },
  header: { height: 56, paddingHorizontal: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  back: { color: C.text, fontSize: 24 },
  title: { color: C.text, fontWeight: '900', fontSize: 17 },
  body: { paddingHorizontal: 18, paddingBottom: 36, gap: 12 },
  badge: { alignSelf: 'flex-start', borderWidth: 1, borderColor: '#ffa03255', backgroundColor: '#ffa03218', paddingHorizontal: 9, paddingVertical: 4, borderRadius: 20 },
  badgeText: { color: C.orange, fontSize: 10, fontWeight: '900' },
  tabs: { flexDirection: 'row', gap: 6, backgroundColor: C.card2, borderRadius: 10, padding: 4 },
  tab: { flex: 1, paddingVertical: 8, borderRadius: 8, alignItems: 'center' },
  tabOn: { backgroundColor: C.purple },
  tabTxt: { color: C.sub, fontSize: 12, fontWeight: '900' },
  tabTxtOn: { color: 'white' },
  card: { backgroundColor: C.card, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: C.border, gap: 10 },
  cardTitle: { color: C.text, fontSize: 13, fontWeight: '900' },
  sub: { color: C.sub, fontSize: 11, lineHeight: 16 },
  between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
  arrow: { color: C.sub, fontSize: 18 },
  divider: { height: 1, backgroundColor: C.border },
  empty: { color: C.sub, textAlign: 'center', paddingVertical: 10 },
  kpiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  kpi: { width: '48%', backgroundColor: C.card, borderRadius: 12, padding: 12, borderWidth: 1, borderColor: C.border, flexDirection: 'row', gap: 10, alignItems: 'center' },
  kIcon: { fontSize: 22 },
  kVal: { fontSize: 16, fontWeight: '900' },
  kLab: { color: C.sub, fontSize: 11 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  chip: { paddingHorizontal: 11, paddingVertical: 6, borderRadius: 20, backgroundColor: C.soft, borderWidth: 1, borderColor: C.border },
  chipOn: { backgroundColor: C.purple, borderColor: C.purple },
  chipText: { color: C.sub, fontSize: 11, fontWeight: '800' },
  chipTextOn: { color: 'white' },
  radar: { height: 165, alignItems: 'center', justifyContent: 'center' },
  rLineV: { position: 'absolute', width: 1, height: 120, backgroundColor: C.border },
  rLineH: { position: 'absolute', width: 150, height: 1, backgroundColor: C.border },
  rLineA: { position: 'absolute', width: 135, height: 1, backgroundColor: C.border, transform: [{ rotate: '35deg' }] },
  rLineB: { position: 'absolute', width: 135, height: 1, backgroundColor: C.border, transform: [{ rotate: '-35deg' }] },
  rBase: { width: 82, height: 82, borderRadius: 16, borderWidth: 2, borderColor: '#7c6fcd55', transform: [{ rotate: '45deg' }] },
  rNow: { position: 'absolute', width: 112, height: 112, borderRadius: 18, borderWidth: 2, borderColor: C.purple, backgroundColor: '#7c6fcd14', transform: [{ rotate: '45deg' }] },
  rLab: { position: 'absolute', color: C.text, fontSize: 10, fontWeight: '800' },
  rp0: { top: 0 }, rp1: { top: 35, right: 0 }, rp2: { bottom: 35, right: 0 }, rp3: { bottom: 0 }, rp4: { bottom: 35, left: 0 }, rp5: { top: 35, left: 0 },
  legend: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  legendText: { color: C.sub, fontSize: 10, fontWeight: '800' },
  measureGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  measure: { width: '48%', backgroundColor: C.card2, borderRadius: 10, padding: 10, borderWidth: 1, borderColor: C.border },
  mName: { color: C.text, fontSize: 11, fontWeight: '900' },
  mBase: { color: C.sub, fontSize: 10, marginTop: 4 },
  mNow: { color: C.text, fontSize: 12, fontWeight: '900' },
  mDiff: { fontSize: 10, fontWeight: '900', marginTop: 4 },
  recent: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 9, borderTopWidth: 1, borderTopColor: C.border },
  dateBox: { width: 40, borderRadius: 8, backgroundColor: C.card2, alignItems: 'center', paddingVertical: 6 },
  dateM: { color: C.sub, fontSize: 9 },
  dateD: { color: C.purple, fontSize: 16, fontWeight: '900' },
  rTitle: { color: C.text, fontSize: 13, fontWeight: '800' },
  rSub: { color: C.sub, fontSize: 11 },
  dropWrap: { gap: 6 },
  tiny: { color: C.sub, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  selectBtn: { backgroundColor: C.card2, borderWidth: 1, borderColor: C.border, borderRadius: 10, padding: 11, flexDirection: 'row', justifyContent: 'space-between' },
  selectTxt: { color: C.text, fontSize: 12, fontWeight: '800' },
  dropdown: { backgroundColor: C.card2, borderWidth: 1, borderColor: C.border, borderRadius: 10, padding: 8, gap: 6 },
  input: { backgroundColor: C.bg, color: C.text, borderRadius: 8, borderWidth: 1, borderColor: C.border, paddingHorizontal: 10, paddingVertical: 8, fontSize: 12 },
  dropItem: { padding: 9, borderRadius: 8 },
  dropOn: { backgroundColor: '#7c6fcd22' },
  dropText: { color: C.sub, fontSize: 12 },
  dropTextOn: { color: C.purple },
  common: { flexDirection: 'row', gap: 8, alignItems: 'center', paddingVertical: 8, borderTopWidth: 1, borderTopColor: C.border },
  commonName: { flex: 1, color: C.text, fontSize: 11 },
  commonVal: { color: C.purple, fontSize: 12, fontWeight: '900' },
  delta: { fontSize: 10, fontWeight: '900' },
  primary: { backgroundColor: C.purple, borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  primaryText: { color: 'white', fontWeight: '900' },
  secondary: { backgroundColor: C.card2, borderRadius: 12, paddingVertical: 14, alignItems: 'center', borderWidth: 1, borderColor: C.border },
  secondaryText: { color: C.text, fontWeight: '800' },
  exercise: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.card2, borderRadius: 10, borderWidth: 1, borderColor: C.border, padding: 10 },
  exerciseOn: { borderColor: C.purple, backgroundColor: '#7c6fcd22' },
  exIcon: { fontSize: 20, width: 28, textAlign: 'center' },
  exName: { color: C.text, fontSize: 13, fontWeight: '800' },
  exSub: { color: C.sub, fontSize: 11 },
  check: { color: C.purple, fontSize: 16, fontWeight: '900' },
  posBadge: { fontSize: 13, fontWeight: '900', backgroundColor: '#34d39918', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 10, overflow: 'hidden' },
  chart: { height: 120, backgroundColor: C.card2, borderRadius: 12, padding: 10, borderWidth: 1, borderColor: C.border },
  bars: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', gap: 7 },
  bar: { flex: 1, borderTopLeftRadius: 6, borderTopRightRadius: 6, minHeight: 18 },
  miniGrid: { flexDirection: 'row', gap: 8 },
  mini: { flex: 1, backgroundColor: C.card2, borderRadius: 8, alignItems: 'center', paddingVertical: 9 },
  miniVal: { color: C.purple, fontSize: 14, fontWeight: '900' },
  miniLab: { color: C.sub, fontSize: 9 },
  session: { backgroundColor: C.card2, borderRadius: 10, borderWidth: 1, borderColor: C.border, overflow: 'hidden' },
  sessionHead: { padding: 10, flexDirection: 'row', justifyContent: 'space-between' },
  compDate: { color: C.text, fontSize: 13, fontWeight: '900' },
  compSub: { color: C.sub, fontSize: 11 },
  deltaPill: { fontSize: 12, fontWeight: '900' },
  series: { borderTopWidth: 1, borderTopColor: C.border, padding: 10, gap: 7 },
  tableHead: { flexDirection: 'row' },
  th: { flex: 1, color: C.sub, fontSize: 10, fontWeight: '900', textAlign: 'center' },
  tr: { flexDirection: 'row', backgroundColor: C.card, borderRadius: 8, paddingVertical: 7 },
  td: { flex: 1, color: C.text, fontSize: 11, textAlign: 'center', fontWeight: '800' },
  avg: { flexDirection: 'row', justifyContent: 'space-between', paddingTop: 8, borderTopWidth: 1, borderTopColor: C.border },
  avgText: { color: C.sub, fontSize: 11 },
  avgVal: { color: C.teal, fontWeight: '900' },
  goal: { color: C.purple, fontWeight: '900', fontSize: 11, backgroundColor: '#7c6fcd22', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, overflow: 'hidden' },
  weekChart: { height: 135, flexDirection: 'row', gap: 8, alignItems: 'flex-end', paddingTop: 12 },
  weekCol: { flex: 1, alignItems: 'center', gap: 5 },
  weekTrack: { width: '100%', height: 100, backgroundColor: C.card2, borderRadius: 7, justifyContent: 'flex-end', overflow: 'hidden' },
  weekBar: { width: '100%', borderTopLeftRadius: 7, borderTopRightRadius: 7 },
  weekTxt: { color: C.sub, fontSize: 9 },
  topGrid: { flexDirection: 'row', gap: 10 },
  topCard: { flex: 1, backgroundColor: C.card, borderRadius: 14, padding: 12, borderWidth: 1, borderColor: C.border, gap: 8 },
  compact: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  compactN: { color: C.purple, fontSize: 10, fontWeight: '900' },
  compactL: { flex: 1, color: C.text, fontSize: 10, fontWeight: '800' },
  compactV: { color: C.green, fontSize: 10, fontWeight: '900' },
  overlay: { flex: 1, backgroundColor: '#00000099', justifyContent: 'flex-end' },
  sheet: { backgroundColor: C.card, borderTopLeftRadius: 20, borderTopRightRadius: 20, borderWidth: 1, borderColor: C.border, padding: 18, paddingBottom: 30, gap: 12 },
  handle: { width: 38, height: 4, borderRadius: 2, backgroundColor: C.border, alignSelf: 'center' },
  modalTitle: { color: C.text, fontSize: 16, fontWeight: '900' },
  close: { color: C.purple, fontWeight: '900' },
  exportGrid: { flexDirection: 'row', gap: 10 },
  exportOpt: { flex: 1, backgroundColor: C.card2, borderRadius: 12, borderWidth: 1, borderColor: C.border, padding: 14, alignItems: 'center', gap: 6 },
  exportOn: { borderColor: C.purple, backgroundColor: '#7c6fcd22' },
  exportIcon: { fontSize: 26 },
  exportText: { color: C.sub, fontWeight: '900' },
  miniTabs: { flexDirection: 'row', gap: 5, backgroundColor: C.card2, padding: 3, borderRadius: 8 },
  miniTab: { flex: 1, alignItems: 'center', paddingVertical: 7, borderRadius: 6 },
  miniOn: { backgroundColor: C.purple },
  miniTxt: { color: C.sub, fontSize: 11, fontWeight: '900' },
  rank: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 9, borderTopWidth: 1, borderTopColor: C.border },
  rankNum: { width: 28, height: 28, borderRadius: 14, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center' },
  rankNumT: { color: C.purple, fontWeight: '900' },
  rankLabel: { color: C.text, fontSize: 12, fontWeight: '900' },
  rankVal: { color: C.green, fontSize: 13, fontWeight: '900' },
});
