import { StyleSheet } from 'react-native';

export const C = {
  bg: '#13132a',
  surface: '#20202b',
  card: '#292934',
  soft: '#333342',
  border: '#3a3a49',
  text: '#ffffff',
  sub: '#9a9aa8',
  muted: '#747483',
  purple: '#7c6fcd',
  teal: '#5eead4',
  orange: '#ffa032',
  green: '#34d399',
  red: '#f87171',
  blue: '#60a5fa',
};

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  header: {
    paddingTop: 50,
    paddingHorizontal: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.bg,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: { color: C.text, fontSize: 22, fontWeight: '800', marginTop: -2 },
  headerTitle: { color: C.text, fontSize: 18, fontWeight: '900' },
  headerAction: {
    minWidth: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  headerActionText: { color: C.teal, fontSize: 11, fontWeight: '900' },
  bellDot: {
    position: 'absolute',
    top: 5,
    right: 5,
    minWidth: 15,
    height: 15,
    borderRadius: 8,
    paddingHorizontal: 3,
    backgroundColor: C.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellDotText: { color: C.text, fontSize: 8, fontWeight: '900' },
  content: { padding: 18, paddingBottom: 44 },
  hero: {
    backgroundColor: C.card,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 14,
    overflow: 'hidden',
  },
  heroRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  heroBadge: { color: C.teal, fontSize: 10, fontWeight: '900', letterSpacing: 0.4, marginBottom: 7 },
  heroTitle: { color: C.text, fontSize: 22, fontWeight: '900', lineHeight: 27 },
  heroSub: { color: C.sub, fontSize: 12, lineHeight: 18, marginTop: 6 },
  heroIcon: {
    width: 62,
    height: 62,
    borderRadius: 20,
    backgroundColor: 'rgba(124,111,205,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(124,111,205,0.42)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 5, marginBottom: 10 },
  sectionTitle: { color: C.text, fontSize: 15, fontWeight: '900' },
  sectionLink: { color: C.purple, fontSize: 11, fontWeight: '900' },
  sectionLabel: { color: C.sub, fontSize: 11, fontWeight: '900', letterSpacing: 0.5, textTransform: 'uppercase' },
  statsRow: { flexDirection: 'row', gap: 9, marginBottom: 16 },
  statCard: {
    flex: 1,
    backgroundColor: C.card,
    borderRadius: 15,
    paddingVertical: 13,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: C.border,
  },
  statValue: { color: C.text, fontSize: 21, fontWeight: '900' },
  statLabel: { color: C.muted, fontSize: 9, fontWeight: '800', marginTop: 3 },
  card: {
    backgroundColor: C.card,
    borderRadius: 17,
    padding: 15,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 11,
  },
  cardAccent: { backgroundColor: 'rgba(124,111,205,0.12)', borderColor: 'rgba(124,111,205,0.35)' },
  row: { flexDirection: 'row', alignItems: 'center' },
  iconBox: {
    width: 45,
    height: 45,
    borderRadius: 14,
    backgroundColor: C.soft,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navTitle: { color: C.text, fontSize: 14, fontWeight: '900' },
  navSub: { color: C.sub, fontSize: 11, lineHeight: 16, marginTop: 3 },
  arrow: { color: C.muted, fontSize: 23, fontWeight: '400' },
  horizontalContent: { paddingRight: 18 },
  activeFriend: {
    width: 112,
    backgroundColor: C.card,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: C.border,
    marginRight: 9,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: C.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarSmall: { width: 36, height: 36, borderRadius: 18 },
  avatarLarge: { width: 52, height: 52, borderRadius: 26 },
  avatarText: { color: C.text, fontSize: 13, fontWeight: '900' },
  onlineDot: {
    position: 'absolute',
    right: -1,
    bottom: -1,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: C.green,
    borderWidth: 2,
    borderColor: C.card,
  },
  friendName: { color: C.text, fontSize: 12, fontWeight: '900', marginTop: 8 },
  friendMeta: { color: C.teal, fontSize: 9, fontWeight: '800', marginTop: 3 },
  activityRow: { flexDirection: 'row', gap: 11, paddingVertical: 11, borderTopWidth: 1, borderTopColor: C.border },
  activityTitle: { color: C.text, fontSize: 12, fontWeight: '800', lineHeight: 17 },
  activityTime: { color: C.muted, fontSize: 10, marginTop: 3 },
  progressTrack: { height: 7, borderRadius: 4, backgroundColor: C.soft, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 4, backgroundColor: C.purple },
  input: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 13,
    color: C.text,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 13,
    marginBottom: 11,
  },
  chips: { flexDirection: 'row', gap: 7, marginBottom: 13 },
  chip: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
  },
  chipOn: { backgroundColor: 'rgba(124,111,205,0.2)', borderColor: C.purple },
  chipText: { color: C.muted, fontSize: 10, fontWeight: '900' },
  chipTextOn: { color: C.text },
  userCard: {
    backgroundColor: C.card,
    borderRadius: 17,
    padding: 14,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 10,
  },
  userTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  userName: { color: C.text, fontSize: 14, fontWeight: '900' },
  userMeta: { color: C.sub, fontSize: 10, marginTop: 3, lineHeight: 15 },
  statusPill: { alignSelf: 'flex-start', marginTop: 7, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, backgroundColor: C.surface },
  statusText: { color: C.sub, fontSize: 9, fontWeight: '900' },
  actionsRow: { flexDirection: 'row', gap: 7, marginTop: 12 },
  primaryBtn: { backgroundColor: C.purple, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 9, alignItems: 'center', justifyContent: 'center' },
  primaryBtnText: { color: C.text, fontSize: 11, fontWeight: '900' },
  secondaryBtn: { backgroundColor: C.surface, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 9, borderWidth: 1, borderColor: C.border, alignItems: 'center', justifyContent: 'center' },
  secondaryBtnText: { color: C.sub, fontSize: 11, fontWeight: '900' },
  successBtn: { backgroundColor: C.green },
  successBtnText: { color: '#10251d' },
  dangerBtn: { backgroundColor: 'rgba(248,113,113,0.12)', borderColor: 'rgba(248,113,113,0.4)' },
  dangerBtnText: { color: C.red },
  empty: { alignItems: 'center', paddingVertical: 34 },
  emptyIcon: { fontSize: 38, marginBottom: 8 },
  emptyText: { color: C.sub, fontSize: 13, fontWeight: '800' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.72)', justifyContent: 'flex-end' },
  modalCard: { backgroundColor: C.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderColor: C.border, padding: 20, paddingBottom: 30 },
  modalHandle: { width: 42, height: 4, borderRadius: 2, backgroundColor: C.border, alignSelf: 'center', marginBottom: 16 },
  modalTitle: { color: C.text, fontSize: 18, fontWeight: '900' },
  modalSub: { color: C.sub, fontSize: 11, lineHeight: 17, marginTop: 4, marginBottom: 14 },
  groupCard: { backgroundColor: C.card, borderRadius: 18, borderWidth: 1, borderColor: C.border, marginBottom: 11, overflow: 'hidden' },
  groupMain: { padding: 14, flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  groupTitle: { color: C.text, fontSize: 15, fontWeight: '900' },
  groupMeta: { color: C.sub, fontSize: 10, marginTop: 3 },
  groupDescription: { color: C.sub, fontSize: 11, lineHeight: 16, marginTop: 7 },
  groupDetails: { borderTopWidth: 1, borderTopColor: C.border, padding: 14, backgroundColor: C.surface },
  miniAvatars: { flexDirection: 'row', alignItems: 'center' },
  miniAvatar: { width: 28, height: 28, borderRadius: 14, backgroundColor: C.purple, borderWidth: 2, borderColor: C.card, alignItems: 'center', justifyContent: 'center', marginRight: -6 },
  miniAvatarText: { color: C.text, fontSize: 8, fontWeight: '900' },
  infoPill: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, backgroundColor: C.surface },
  infoPillText: { color: C.teal, fontSize: 9, fontWeight: '900' },
  rankingHero: { backgroundColor: 'rgba(255,160,50,0.10)', borderColor: 'rgba(255,160,50,0.35)' },
  periodToggle: { flexDirection: 'row', backgroundColor: C.surface, borderRadius: 12, padding: 4, marginBottom: 10 },
  periodBtn: { flex: 1, paddingVertical: 8, borderRadius: 9, alignItems: 'center' },
  periodBtnOn: { backgroundColor: C.card },
  periodText: { color: C.muted, fontSize: 10, fontWeight: '900' },
  periodTextOn: { color: C.orange },
  rankRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 12, borderTopWidth: 1, borderTopColor: C.border },
  rankMe: { backgroundColor: 'rgba(124,111,205,0.14)', marginHorizontal: -8, paddingHorizontal: 8, borderRadius: 12 },
  rankPos: { width: 26, color: C.sub, fontSize: 14, fontWeight: '900', textAlign: 'center' },
  rankName: { color: C.text, fontSize: 13, fontWeight: '900' },
  rankExtra: { color: C.sub, fontSize: 10, marginTop: 3 },
  rankValue: { color: C.teal, fontSize: 11, fontWeight: '900', textAlign: 'right' },
  trendUp: { color: C.green },
  compareBox: { backgroundColor: 'rgba(94,234,212,0.09)', borderColor: 'rgba(94,234,212,0.28)' },
  notificationCard: { backgroundColor: C.card, borderRadius: 17, padding: 14, borderWidth: 1, borderColor: C.border, marginBottom: 10, flexDirection: 'row', gap: 12 },
  notificationUnread: { backgroundColor: 'rgba(124,111,205,0.12)', borderColor: 'rgba(124,111,205,0.55)' },
  unreadDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: C.teal, marginTop: 4 },
  notificationTitle: { color: C.text, fontSize: 13, fontWeight: '900', lineHeight: 17 },
  notificationSub: { color: C.sub, fontSize: 10, lineHeight: 15, marginTop: 3 },
  notificationTime: { color: C.muted, fontSize: 9, marginTop: 5 },
  privacySummary: { backgroundColor: 'rgba(124,111,205,0.13)', borderColor: 'rgba(124,111,205,0.35)' },
  optionCard: { backgroundColor: C.card, borderRadius: 17, padding: 14, borderWidth: 1, borderColor: C.border, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 12 },
  optionTitle: { color: C.text, fontSize: 13, fontWeight: '900' },
  optionSub: { color: C.sub, fontSize: 10, lineHeight: 15, marginTop: 3 },
  switchTrack: { width: 48, height: 28, borderRadius: 14, backgroundColor: C.soft, padding: 4, justifyContent: 'center' },
  switchTrackOn: { backgroundColor: C.purple },
  switchKnob: { width: 20, height: 20, borderRadius: 10, backgroundColor: C.sub },
  switchKnobOn: { alignSelf: 'flex-end', backgroundColor: C.text },
  locked: { opacity: 0.65 },
  warning: { backgroundColor: 'rgba(248,113,113,0.08)', borderColor: 'rgba(248,113,113,0.3)' },
  warningTitle: { color: C.red, fontSize: 12, fontWeight: '900' },
  warningText: { color: C.sub, fontSize: 10, lineHeight: 16, marginTop: 5 },
});
